const PDFDocument = require("pdfkit");

const generateOrderPDF = (order, res) => {
  try {
    const doc = new PDFDocument({
      margin: 50,
      size: "A4",
    });

    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${order.bookingNumber}.pdf`
    );

    doc.on("error", (err) => {
      console.error("PDF Error:", err);
    });

    doc.pipe(res);

    // Title
    doc
      .fontSize(22)
      .text("Sales Order", {
        align: "center",
      });

    doc.moveDown();

    // Company Info
    doc
      .fontSize(14)
      .text("Company Information");

    doc.fontSize(12);
    doc.text("Tech Ecosystem LLC");
    doc.text("Muscat, Oman");

    doc.moveDown();

    // Order Details
    doc
      .fontSize(14)
      .text("Order Details");

    doc.fontSize(12);

    doc.text(
      `Order Number: ${
        order.bookingNumber || "N/A"
      }`
    );

    doc.text(
      `Customer: ${
        order.customer?.customerName ||
        "Customer Not Found"
      }`
    );

    doc.text(
      `Sales Person: ${
        order.salesPerson || "N/A"
      }`
    );

    doc.text(
      `Order Date: ${
        order.orderDate
          ? new Date(
              order.orderDate
            ).toDateString()
          : "N/A"
      }`
    );

    doc.text(
      `Delivery Date: ${
        order.deliveryDate
          ? new Date(
              order.deliveryDate
            ).toDateString()
          : "N/A"
      }`
    );

    doc.moveDown();

    // Products Section
    doc
      .fontSize(14)
      .text("Products");

    doc.moveDown(0.5);

    if (
      order.items &&
      order.items.length > 0
    ) {
      order.items.forEach(
        (item, index) => {
          doc.text(
            `${index + 1}. ${
              item.product?.productName ||
              "Product Not Found"
            }`
          );

          doc.text(
            `   Qty: ${
              item.quantity || 0
            }`
          );

          doc.text(
            `   Rate: ${
              item.rate || 0
            }`
          );

          doc.text(
            `   Discount: ${
              item.discount || 0
            }%`
          );

          doc.text(
            `   FOC: ${
              item.focQuantity || 0
            }`
          );

          doc.moveDown(0.5);
        }
      );
    } else {
      doc.text(
        "No products available."
      );
    }

    doc.moveDown();

    // Summary
    doc
      .fontSize(14)
      .text("Order Summary");

    doc.fontSize(12);

    doc.text(
      `Gross Amount: ${
        order.grossAmount || 0
      }`
    );

    doc.text(
      `Total Discount: ${
        order.totalDiscount || 0
      }`
    );

    doc.text(
      `Total FOC: ${
        order.totalFOC || 0
      }`
    );

    doc.text(
      `Grand Total: ${
        order.grandTotal || 0
      }`
    );

    doc.moveDown();

    doc
      .fontSize(10)
      .text(
        "Generated by Sales Order Management System",
        {
          align: "center",
        }
      );

    doc.end();
  } catch (error) {
    console.error(
      "PDF Generation Error:",
      error
    );

    if (!res.headersSent) {
      res.status(500).json({
        message:
          "Failed to generate PDF",
      });
    }
  }
};

module.exports = generateOrderPDF;